Repository unb-mds/2024-2-ChamaControl, pull requests merged in 2024-11, with the labels that each got.

#8 github(issue): define o template para as issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs-repair.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/rabbit.md
  .github/ISSUE_TEMPLATE/task.md
Labels: documentation

#9 docs: criar estudo sobre metodologias ágeis
  docs/estudos/Metodologias_ágeis.md
Labels: documentation

#11 docs(template): cria o template de commit
  .github/COMMIT_TEMPLATE/README.md
Labels: documentation

#14 Docs/issue-10/cria templates
  .github/pull_request_template.md
  docs/sprints/template_sprint.md
Labels: documentation

#16 add docs coelho requisitos
  docs/estudos/coelhos/requisitos.md
Labels: documentation, Estudos 📚, rabbit

#17 atualiza docs arquitetura
  docs/estudos/coelhos/arquitetura.md
Labels: documentation, Estudos 📚

#20 Mkdocs
  .github/.gitattributes
  docs/index.md
  mkdocs.yml
Labels: documentation

#29 docs(estudos): cria o estudo sobre ambiente de desenvolvimento
  docs/estudos/coelhos/ambiente-de-desenvolvimento.md
Labels: documentation, rabbit

#30 docs(arquitetura): cria a primeira documentacao da arquitetura
  docs/arquitetura/arquitetura.md
  docs/arquitetura/diagrama.png
Labels: documentation

#33 docs/sprints/finaliza-sprint-2-e-cria sprint-3
  docs/sprints/Sprint-2.md
  docs/sprints/Sprint-3.md
Labels: documentation
